### ISSUE TITLE
Help with warning when compiling

### ISSUE THREAD

**Issue by vpont** [BathroomEpiphanies/epiphanies_tmk_keyboard#2]
Hi Fredrik!

A "few" years ago I bought your Pegasus Hoof controller (2013) and I'm having difficulties compiling the latest git revision of [qmk_firmware](https://github.com/qmk/qmk_firmware) for this firmware.

After compiling and flashing I noticed the keys where not correctly assigned and after taking a look at the source code I noticed that the [current implementation of Pegasus Hoof 2013](https://github.com/qmk/qmk_firmware/tree/master/keyboards/bpiphany/pegasushoof/2013) is indeed wrong. PINs and ports are different from those [in your code](https://github.com/BathroomEpiphanies/epiphanies_tmk_keyboard/blob/master/be_controllers/config_pegasus_hoof_20131001.h).

I've modified qmk's implementation with your bits, but there's a warning that stops it from compiling and I wanted to know if you'd be so kind to help me out:

This is my repo with the corrections:
https://github.com/vpont/qmk_firmware/blob/master/keyboards/bpiphany/pegasushoof/2013_fix

The warning message complains at this line:

`DDRB  &= ~0b11111111;`

as seen here:

```
./bin/qmk compile -kb bpiphany/pegasushoof/2013_fix --keymap victor

Ψ Compiling keymap with make bpiphany/pegasushoof/2013_fix:victor

QMK Firmware 0.10.24
Making bpiphany/pegasushoof/2013_fix with keymap victor

avr-gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  24398	      0	  24398	   5f4e	.build/bpiphany_pegasushoof_2013_fix_victor.hex

Compiling: keyboards/bpiphany/pegasushoof/2013_fix/matrix.c
keyboards/bpiphany/pegasushoof/2013_fix/matrix.c: In function 'matrix_init':
keyboards/bpiphany/pegasushoof/2013_fix/matrix.c:70:11: error: overflow in conversion from 'int' to 'uint8_ ' {aka 'volatile unsigned char'} changes value from '(int)*36 & -256' to '0' [-Werror=overflow]
   70 |  DDRB  &= ~0b11111111;
      |           ^
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:386: .build/obj_bpiphany_pegasushoof_2013_fix_victor/matrix.o] Error 1
Make finished with errors
make: *** [Makefile:584: bpiphany/pegasushoof/2013_fix:victor] Error 1
```

Thank you in advance!

**Comment by vpont** [comment]
Just an update, I tried with:
`DDRB &= ~0b01111111;`

And it compiles and works perfectly, but I'm not sure this initialization is fine.
Can you please confirm? Thanks!

**Comment by BathroomEpiphanies** [comment]
Hi,

You are probably better off asking the creator of qmk, and you should
submit your fixes to his git repository if you get them working =)

I'm not very proficient in c either, but I would try something like

DDRB  &= ~(uint8_t)(0b11111111)

If I understand the error message at all the compiler is worrying
about 0b11111111 being a signed integer, that is later used as an
unsigned. A "naked" integer is parsed as the type 'int' I _believe_.

Hope that helps.

Fredrik

**Comment by vpont** [comment]
It throws the same warning with the line you suggested.
I think the right casting would be this:
`DDRB  &= (unsigned char)~0b11111111;`

I'm very surprised noone has noticed qmk's implementation of Pegasus Hoof 2013 is not correct.
I'll make the changes and submit a PR.
Thanks for your reply anyway, I hope you're doing great!
